# .github/workflows/main.yml
name: Trigger Netlify Build
on:
  schedule:
    # Run at 10:05 every Sunday
    - cron: '5 10 * * sun'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{secrets.NETLIFY_BUILD_HOOK}}
